language: c

before_install:
  - mozroots --import --sync
  - chmod +x scripts/mono.sh
  - chmod +x lib/xunit/xunit.console.clr4.exe
  - export EnableNuGetPackageRestore=true  
  - sudo ./scripts/mono.sh

script:
  - cd src/
  - xbuild GitHubPushLib.sln
  - mono ../lib/xunit/xunit.console.clr4.exe GitHubPushLib.Tests/bin/Debug/GitHubPushLib.Tests.dll